### PR TITLE
Suggestion README.md

### PR DESCRIPTION
**Pull request by Amoranemix**
Suggestion see file.

### CODE REVIEW

**Comment by tannertechnology** [comment]
This pr needs to be modified to actually include an explanation or closed without merging. See the Issues section for things like this.

**Comment by Amoranemix** [comment]
> This pr needs to be modified to actually include an explanation or closed without merging. See the Issues section for things like this.

What do you mean? Isn't it obvious? Isn't the idea that people can install the mods from that list? If so, then it should be explained to them how to do that.

**Comment by tannertechnology** [comment]
Pull requests are for you to request your code/change be merged into the project. Look at the top of the page for the Issues section. You should create an issue instead or otherwise submit a useful pull request. https://github.com/LeArby/OpenMW-Enhanced/issues

**Comment by Amoranemix** [comment]
OK. I'll try to add my suggestion as an issue.

**Pull request closed without merging**
